### ISSUE TITLE
Proposal: Consolidate geospatial samples into single top-level folder

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/samples#43]
I think we should move GeofenceMarketing and MapViewerSample under the Geospatial folder. 

@chanskw What do you think?

**Comment by chanskw** [comment]
+1, would you be able to update article link?

I also think we need to keep the current link working... as this is being linked to from Youtube as well.

**Comment by Alex-Cook4** [comment]
Any ideas on how to keep the current link working without keeping the sample there?

**Comment by natashadsilva** [comment]
+1 @chanskw which video on Youtube does it link to? This video https://www.youtube.com/watch?v=dg7Xs6lE63U&feature=youtu.be and it links to streamsdev and not the sample itself.

**Comment by natashadsilva** [comment]
Done.
