### ISSUE TITLE
Is WindowEvents still relevant? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/samples#44]
WindowTest sample should have a README.md pointing to the article at the very least. 

We should also figure out if this sample/article is still relevant.  https://github.com/IBMStreams/samples/tree/master/WindowTest

**Comment by Alex-Cook4** [comment]
Closer look shows that this is an example for windowing using a Java operator.

**Comment by natashadsilva** [comment]
Still relevant, closing issue.
