### ISSUE TITLE
Need README.md files for Timeseries samples

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/samples#47]
https://github.com/IBMStreams/samples/tree/master/timeseries

Need README.md's with a format of:
1. Brief intro to what this sample is
2. Instructions for building, submitting, and confirming that it worked.

**Comment by Alex-Cook4** [comment]
@chanskw Do you know who developed these?

**Comment by natashadsilva** [comment]
Fixed in Pull request #64
