### ISSUE TITLE
Predictive Blacklisting sample does not work with current maxmind database

### ISSUE THREAD

**Issue by bbrown777** [IBMStreams/samples#53]
IPSpatialEnricherOp fails with current database downloaded from Maxmind.  An older version of
the database works fine that I saved back earlier in the year.  The problem occurs with both 4.1 and
4.1.1 of the Streams QSE.

**Comment by chanskw** [comment]
@cancilla Can you please take a look?

**Comment by cancilla** [comment]
The problem is with the IPSpatialEnricher operator in the network toolkit. I've opened the following issue in that repository: https://github.com/IBMStreams/streamsx.network/issues/55

**Comment by cancilla** [comment]
I delivered a fix to the com.ibm.streamsx.network toolkit. I have also generated a new release, v2.8.3, that includes this fix. Please give it a try and if you are still running into problems, let me know.

**Comment by bbrown777** [comment]
It works!!!  Thank you James and IBM team!


Best Regards,

Bruce



Bruce Brown, BigData Systems Engineer, Co-Author of Hadoop for Dummies 
Jeskell Systems, LLC / An IBM Premier Business Partner
315-263-4212 (c)
bbrown@jeskell.com
