### ISSUE TITLE
Where can I find these samples? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/samples#65]
There used to be these examples in the Examples for Beginners: 

058_data_sharing_between_non_fused_spl_custom_and_cpp_primitive_operators
 
061_data_sharing_between_non_fused_spl_custom_operators_and_a_native_function
 
062_data_sharing_between_non_fused_spl_custom_and_java_primitive_operators

Is there a way for me to find them now? Why were they removed?

**Comment by natashadsilva** [comment]
They have been  updated and are now part of the DPS toolkit:
You can get them here:
https://github.com/IBMStreams/streamsx.dps/tree/master/samples
and here: 
https://github.com/IBMStreams/streamsx.dps/tree/master/extraSamples/DPSFunctionDemo 
and
