### ISSUE TITLE
Add catalog entry for Patients Monitoring Demo

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/samples#69]
https://github.com/IBMStreams/streamsx.health/tree/develop/samples/PatientsMonitoringDemo

This demo showcases the health toolkit as well as the rules compiler support.

**Comment by natashadsilva** [comment]
@chanskw Does it run in Bluemix?

**Comment by chanskw** [comment]
No, not yet... i tried it but could not get tuple inject to work on Bluemix
