### ISSUE TITLE
Test, update and release samples for Streams 4.2.1.1

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/samples#76]
Some of the samples are out-of-date and no longer run.
Need to go through the samples to update them.

Need to think of a release strategy for us to be in sync with Streams product release.  i.e. we should take a snapshot of the samples and make a release after we have made sure that all the samples work for a particular version of Streams.

**Comment by markheger** [comment]
samples have been updated since 2017

there is still a gap of test suite, issue #105 is one step towards this
