### ISSUE TITLE
What is the buffersize unit?

### ISSUE THREAD

**Issue by just4li** [IBMStreams/samples#84]
bufferSize
Specifies the size of each buffer that is used to store the input tuples for each output port. The final punctuation marker is not forwarded until all buffers are drained.

So what is the unit? KB? MB? GB? or just bytes?

**Comment by natashadsilva** [comment]
@just4li which toolkit/sample are you referring to?

**Comment by just4li** [comment]
https://github.com/IBMStreams/samples/tree/master/Examples-for-beginners/024_threaded_split_at_work

**Comment by natashadsilva** [comment]
@just4li  The `bufferSize` specifies the number of tuples and punctuations that can be held for each output port.
