### ISSUE TITLE
Update to UpperRest.spl sample file

### ISSUE THREAD

**Issue by nmwaara** [IBMStreams/samples#85]
I was trying to run the UpperRest.spl file using the latest 2.9.6 release and was having issues with the use directives at the top of the file. I had to update the use directives to be as follows in order to properly compile my spl file...

use com.ibm.streamsx.inet.rest::HTTPRequest;
use com.ibm.streamsx.inet.http::HTTPResponse;
use com.ibm.streamsx.inet.rest::HTTPRequestProcess;

This may need to be updated in the sample code for proper compiling of the sample. Let me know if you need any clarification on the issue I was running into.

**Comment by natashadsilva** [comment]
@nmwaara Sorry for the delay; could you please clarify whether it is a problem with using the latest version of the inet toolkit?
@siegenth FYI

**Comment by nmwaara** [comment]
I do believe it is a problem when using the latest version of the toolkit with this specific sample. It has been some time since I looked into this, but after looking over a few things, I believe that is the case. The issue is that in older releases of the inet toolkit, there was a com.ibm.streamsx.inet.http::HTTPRequest that could be sourced, but that was moved to com.ibm.streamsx.inet.rest::HTTPRequest. That was the main issue I was running into if I remember correctly. 

I just took another look at the newest release of the toolkit, and it states, "The http rest functions and the WebSocket server functions are now moved into streamsx.inetserver toolkit," so possibly this will need to be updated differently based on that? I would need to look into this more to be totally sure.

**Comment by ashersilver** [comment]
I am having exactly the same problem no matter which version of the toolkit I use.
I uncomment the following statement from the main spl:
use com.ibm.streamsx.inet.rest::*;
... and uncomment the other code as per the instructions ... 

Here is the consol output:

com.acme.test/WebCalculator.spl:99:5: CDISP0760W WARNING: The com.ibm.streamsx.inet.rest namespace is not defined in the use directive.
com.acme.test/WebCalculator.spl:124:31: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: HTTPTupleInjection.
com.acme.test/WebCalculator.spl:176:20: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: HTTPTupleView.

I dont know where the HTTPTupleInjection is defined but I dont see it in any of the searches ...

**Comment by joergboe** [comment]
The UpperRest demo depends now on streamsx.inetserver toolkit and the 
stream type HTTPRequest id defined in inet server toolkit thus use the following imports :
use com.ibm.streamsx.inet.rest::HTTPRequestProcess ;
use com.ibm.streamsx.inet.rest::HTTPRequest ;

**Comment by markheger** [comment]
* most of the samples have already inet dependency [2.0.0,3.0.0) in info.xml
* comment needs to be added for UpperRest.spl
