### ISSUE TITLE
Add Event Streams --> COS demo to Samples Catalog

### ISSUE THREAD

**Issue by markheger** [IBMStreams/samples#87]
Please add the following demo to the Samples Catalog:
https://github.com/IBMStreams/streamsx.objectstorage/tree/master/demo/data.historian.event.streams.cos.exactly.once.semantics.demo

**Comment by markheger** [comment]
Per instructions, there are two options to add a sample:

_1) You can create a pull request so that the sample will be hosted in this repository.
2) If the sample is already hosted in another repository on GitHub, you can also just add it to the catalog by opening an issue._

I want to choose option 2 with this issue, hence there is no pull request.

**Comment by markheger** [comment]
Proposed title of the sample:
"High volume message upload with Streaming Analytics and exactly once semantics"

**Comment by natashadsilva** [comment]
Hi Mark you're right, sorry I didn't understand. Will take a look when I can.

**Comment by natashadsilva** [comment]
Updated.
