### ISSUE TITLE
Add SSEClient sample to catalog.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/samples#90]
Sample of using SSClient to read Server-sent events into IBM Streams with a Python topology.

https://gist.github.com/ddebrunner/21db521909accd2ec364861964e18ae3

Language Python
Tags: beginner, ingest

**Comment by ddebrunner** [comment]
Any instructions on how to do this?

**Comment by natashadsilva** [comment]
It was already added. https://ibmstreams.github.io/samples/?filter=server

**Comment by ddebrunner** [comment]
@natashadsilva  Thanks!
